version: "3.8"
services:
  jupyter:
    container_name: jupyter
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    restart: "always"
    env_file:
      - jupyter/jupyter.env
    volumes:
      - ./src:/home/jovyan/src
  s3fs:
    container_name: s3fs
    image: efrecon/s3fs:1.91
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    devices:
      - /dev/fuse
    volumes:
      - ./bucket:/opt/s3fs/bucket
    environment:
      AWS_S3_BUCKET: '${AWS_S3_BUCKET}'
      AWS_S3_ACCESS_KEY_ID: '${AWS_S3_ACCESS_KEY_ID}'
      AWS_S3_SECRET_ACCESS_KEY: '${AWS_S3_SECRET_ACCESS_KEY}'
      AWS_S3_MOUNT: '/opt/s3fs/bucket'
      S3FS_DEBUG: 1
      UID: 1000
      GID: 1000